ios/Flutter/Debug.xcconfig
ios/Flutter/Release.xcconfig
ios/Podfile
lib/main.dart

#29 Issue resolved.

---

lib/providers/manager.dart
lib/screen/General/fullScreenImage.dart
lib/screen/General/homescreen.dart
lib/screen/Posts/feedScreen.dart
lib/screen/Posts/view/viewMyPostsScreen.dart
lib/screen/Posts/view/viewMySavedPosts.dart
lib/screen/Posts/view/viewYourPosts.dart
pubspec.lock
pubspec.yaml

What's new in v1.0.0+4 ?
1. Introducing new bottom navigation bar  
2. Reduces the loading time to fetch feed posts .
3. Fixes the non scrolling followers/followings list .
4. Post images can be now seen on a separate screen .
5. Introduced [Upgrader](https://pub.dev/packages/upgrader) package to notify users about any new version of the app that is available on Google Play Store . ( Not tested yet )

version update to 1.0.0.+4

---

lib/utils/constants.dart
lib/utils/keys.dart
lib/view/screens/Authentication/login_screen.dart
lib/view/screens/Authentication/register_screen.dart
lib/view/screens/HomeNavigation/home_navigation_screen.dart
test/authentication_test.dart
test/home_nav_test.dart

[#68] : written tests for navigation bar functionalities

---

android/app/src/main/AndroidManifest.xml

Fixes:  OnBackInvokedCallback feature is enabled.

[#68 Fixed]: enabled OnBackInvokedCallback feature.

---

lib/controllers/Authentication/auth_screen_controller.dart
lib/view/screens/ProfileScreen/self_profile.dart

This PR completes all the tasks mentioned in the issue and fixes #83

[#83 implemented] : Created modal sheet and added logout button

---

lib/utils/routing.dart
lib/view/screens/ProfileScreen/list_users.dart
lib/view/screens/ProfileScreen/other_profile.dart
lib/view/screens/ProfileScreen/self_profile.dart

[#90 feat] : Creates a new screen to display list of followers/following through self and other profile

---

codemagic.yaml

Updated the codemagic.yaml file to trigger the build when merging with the prod branch instead of main.

#104 updated the codemagic.yaml file

---

android/gradle/wrapper/gradle-wrapper.properties
lib/view/reusable_components/feedbox.dart
lib/view/screens/FeedScreen/feed_screen.dart
macos/Flutter/GeneratedPluginRegistrant.swift
pubspec.lock
pubspec.yaml

This PR creates one or two features of #59

[feat] : working on the UI of feed screen

---

lib/controllers/Authentication/auth_screen_controller.dart
lib/controllers/Authentication/user_controller.dart
lib/services/auth_services.dart
lib/view/reusable_components/feedbox.dart
lib/view/screens/Authentication/login_screen.dart
lib/view/screens/Authentication/register_screen.dart

[#56 feat] : implemented google sign in

---

lib/controllers/PostController/create_post_controller.dart
lib/view/screens/Authentication/register_screen.dart
lib/view/screens/CreatePostScreen/create_post_screen.dart

[#105 feat] : reset create post controller after successful post

---

lib/view/reusable_components/textbox_editprofile.dart
lib/view/screens/ProfileScreen/edit_profile_screen.dart
lib/view/screens/ProfileScreen/more_options_self.dart

[#114] : Implemented a function to Check Unique Username in Database

---

lib/view/screens/Authentication/login_screen.dart
lib/view/screens/Authentication/register_screen.dart

- Standardized name capitalization for users signing up through Gmail to match the format used in the standard sign-up process.
- Ensured the first character of each word in the user’s name is capitalized.
- Updated existing records to correct the capitalisation in the database.
This PR closes #119

[#119 fix] : Fix inconsistency in user name capitalisation from Gmail sign-ups

---

lib/view/screens/ProfileScreen/more_options_other_profile.dart

Added new options to the menu in other's profile:
- Report
- Block
- Share Profile
- Website Link
- Cancel

[#129]: Added new options to the menu in other's profile

---

lib/view/screens/ProfileScreen/more_options_self.dart

- Added 'Settings' option
- Added 'Blocked Contacts' option
- Added 'Help' option
- Added 'About' option

[#132]: Added new menu options to self profile

---

lib/data/post_data.dart
lib/models/notification_model.dart
lib/utils/util_functions.dart
lib/view/reusable_components/notification_box.dart
lib/view/screens/FeedScreen/feed_screen.dart
lib/view/screens/FeedScreen/list_comment_screen.dart
lib/view/screens/NotificationScreen/notification_screen.dart
lib/view/screens/SplashScreen/splash_screen.dart
pubspec.lock
pubspec.yaml

This PR contains the code implementation for adding the notification screen which displays the list of read and unread notification , each notification has its own type - 'comment' , 'like' , 'mention' etc ..

[#new] : created a new screen to display notifications

---

lib/utils/util_functions.dart
lib/view/screens/Authentication/login_screen.dart
lib/view/screens/Authentication/register_screen.dart

[#143] : Implemented functions that generates  unique username and assigns them to user during `registration`

---

lib/data/notification_data.dart
lib/view/reusable_components/notification_box.dart
lib/view/screens/NotificationScreen/notification_screen.dart

[#158 feat] : Allow users to read and delete notifications within the application.

---

lib/view/reusable_components/notification_box.dart

[#164] : navigate to user profile screen from notification screen

---

lib/data/post_data.dart
lib/main.dart
lib/services/custom_notification_service.dart
lib/services/notification_service.dart
lib/view/screens/ChatScreen/inbox_screen.dart

[feat] : Navigate to relevant chat screen on notification click

---

lib/data/chat_data.dart
lib/view/reusable_components/chat_head_container.dart
lib/view/screens/ChatScreen/inbox_screen.dart
lib/view/screens/ChatScreen/more_options_message.dart
pubspec.lock
pubspec.yaml

[#171 feat] : message encryption using `encrypt` library

---

analysis_options.yaml
lib/controllers/PostController/create_post_controller.dart
lib/view/reusable_components/custom_textbox_for_comment.dart
lib/view/reusable_components/mention_user_tile.dart
lib/view/reusable_components/message_container.dart
lib/view/screens/ChatScreen/chat_list_screen.dart
lib/view/screens/CreatePostScreen/add_image_for_post_box.dart
lib/view/screens/SplashScreen/splash_screen.dart

[#175 feat] : remove selected media files using their index

---

lib/view/reusable_components/message_container.dart
lib/view/screens/ChatScreen/inbox_screen.dart

[#194 feat] :  User profile redirection from Chat by clicking username or display picture

---

lib/view/screens/CreatePostScreen/create_post_screen.dart

[#185]: Implemeneted prompt to confirm discarding post on back nav
